# Generated by Django 5.0.1 on 2024-02-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_user_remove_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/producto_defecto.png', upload_to='products'),
        ),
    ]
