# Generated by Django 5.0.1 on 2024-02-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_alter_order_user_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='customer',
        ),
    ]
