# Generated by Django 4.0 on 2024-02-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='petpics')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('breed', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('pathology', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser')),
            ],
        ),
    ]
