# Generated by Django 4.0 on 2024-02-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
